Refatoracao
AmaralUSP/sondaAPI pull request #3
Opened 2022-09-22 18:42 UTC by AmaralUSP

2022-09-22 21:28 UTC, danielqejo commented
teste, pra ver se eu consigo comentar no seu PR

2022-09-22 21:29 UTC, danielqejo commented
@[danielqejo](https://github.com/danielqejo) danielqejo [2 days ago](https://github.com/danielqejo/sondaAPI/pull/1#discussion_r975805498)
O Service parece ter responsabilidades demais, eles:

Valida se a Sonda está ativa (se a Sonda não existe mais, podemos simplesmente não trazer na consulta)
Busca a Sonda através do repository
Movimenta a sonda
Valida diversos estados, talvez devesse ser outra classe que cuida disto.
Desabilita a Sonda
Salva a Sonda
O que eu imagino que esse método moveSonda deveria fazer:

Buscar a Sonda através do repository
Movimentar a Sonda
Pedir pro Repository Salvar a Sonda
Retornar
@[AmaralUSP](https://github.com/AmaralUSP) AmaralUSP [5 hours ago](https://github.com/danielqejo/sondaAPI/pull/1#discussion_r977870238)
boa, eu dividi em dois metodos, move sonda e verifica se o movimento é valido, acredito que assim eu deixo o move sonda apenas com a responsabilidade de mover rs

2022-09-22 22:53 UTC, danielqejo requested changes
Além dos comentários, tem alguns outros pontos:
Importantes:
- Não vi nenhum teste de unidade, seria mais importante do que o teste de integração por enquanto.

- Menos importante
- as convenções de pacotes no java é snake_case
- as pastas target, .idea e etc deveriam estar no gitignore
- o projeto não está na raiz, você pode conferir a do cairolli como ficou
- os testes de integração estão no package root, a convenção é ficar no mesmo package da classe sendo testada

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/Model/SondaService.java
> +    public Sonda create(@Valid Sonda sonda) {
O Service ainda parece que faz coisas demais. Como te expliquei o Service (neste caso, um ApplicationService [da uma olhada nesse ppt do nubank, explica a diferença](https://s3-sa-east-1.amazonaws.com/thedevconf/presentations/TDC2019POA/designcodigo/DCQ-9841_2019-12-01T025820_tdc-nubank-ddd(2).pdf) ) deveria ser uma camada que faz somente alguns passos relacionados a arquitetura do sistema.
Exemplo: Analisar se a posição é válida é uma regra do seu negócio, portanto não deveria estar no Service.

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/campo/Model/CampoService.java
> +    }
O método exist deveria existir?
O getCampoById faz um get no Optional sem olhar se o objeto existe ou não, essas duas coisas estão relacionadas.

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/campo/controller/CampoController.java
> +        return ResponseEntity.ok(campoService.getCampoById(id));
E se voltar null aqui? XD

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/campo/controller/CampoController.java
> +        var sonda = sondaService.create(dto.toEntity(campo));
Vazando muito o encapsulamento aqui, essas 3 etapas poderiam ser feitas dentro do service para garantir que eu não preciso lembrar de rodar um exist antes de rodar os demais comandos.

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/campo/Model/CampoService.java
> +    }
Está mesmo, e o motivo é de que :
- Não é responsabilidade do service fazer isso
- Não é responsabilidade do repository fazer isso
- Mais uma consulta para um dado que você ja tem em mãos no SondaService

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/SondaExceptions/SondaExceptions.java
> +public class SondaExceptions extends RuntimeException{
Essa classe nunca é instanciada, já que as demais herdam eu entendo que deveria ser abstrata.
Além disso, essa classe poderia ser sealed (não permitindo nenhuma outra implementação que não seja uma inner class desta).

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/SondaExceptions/SondaExceptionHandler.java
> +    Logger logger = LoggerFactory.getLogger(SondaExceptionHandler.class);
Geralmente loggers são static, final e private.
O motivo disto é que não é necessário mais de uma instância do logger para aquela classe.

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/controller/SondaController.java
>          }
Na minha opinião isso daqui é bem ineficiente.
Pra todo commando solicitado é uma consulta no banco (fora as que vão rolar dentro do service) :panik:
Seria melhor delegar pra quem vai buscar o objeto do banco e executar tudo de uma vez. (ainda assim eu acharia esquisito no service, porque parece regra de negócio, talvez tenha um objeto faltando pra lidar com o domínio)

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
> +        public abstract int[] movimenta();
Uma orientação pode se movimentar? :thinking:

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
> +    public void desativar(Boolean estaAtivo) {
E se eu passar desativar(true)?

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
> +    public enum direcao {
direção em minusculo

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
> +        public abstract int[] movimenta();
Tanto que você seta as posições de volta na sonda, claramente não é responsabilidade dessa classe XD

2022-09-22 22:53 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/repository/SondaRepository.java
> +
como disse, faz coisas demais, no máximo eu teria um findById aqui e um save

2022-09-23 17:05 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
>      private Campo campo;
acho que o que me confundiu foi aquela questao de que minha Sonda nao necessariamente é o mesmo objeto que esta no banco. Para isso teria que criar um DAO para ele ser esse objeto e depois montar a entidade, ne?

2022-09-27 11:16 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/Model/SondaService.java
> +        sondaRepository.moveSonda(id, pos[0], pos[1]);
resolvido com constraints!

2022-09-27 11:17 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/Model/SondaService.java
> +    public Sonda create(@Valid Sonda sonda) {
agora acredito que os services estao mais enxutos e com menos responsabilidades

2022-09-27 11:17 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/campo/Model/CampoService.java
> +    }
removi esse metodo! ja nao existe mais, realmente nao fazia sentido

2022-09-27 11:18 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/campo/controller/CampoController.java
> +        return ResponseEntity.ok(campoService.getCampoById(id));
agora tratei como optional e se voltar nulo dispara uma excessao e um badrequest

2022-09-27 11:18 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/campo/controller/CampoController.java
> +        var sonda = sondaService.create(dto.toEntity(campo));
agora estao todas dentro do controller!

2022-09-27 11:18 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/campo/Model/CampoService.java
> +    }
agora essa verificacao esta dentro do entity

2022-09-27 11:19 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/SondaExceptions/SondaExceptions.java
> +public class SondaExceptions extends RuntimeException{
mudei para sealed, mas pediu que todas as inner class fossem final, pq?

2022-09-27 11:19 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/SondaExceptions/SondaExceptionHandler.java
> +    Logger logger = LoggerFactory.getLogger(SondaExceptionHandler.class);
boa, nao sabia!

2022-09-27 11:23 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/controller/SondaController.java
>          }
hmm nao consegui pensar em uma logica mais eficiente para isso, pq a logica que esta implementada atualmente foi pensada para lidar com um comando por vez e nao receber todos, executar e voltar. Acho que gastaria bastante mana pra mudar ..... mas posso mudar, nao tem problema

2022-09-27 11:24 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
> +        public abstract int[] movimenta();
mudei para um switch case, nao é muito eficiente pq faz varias verificacoes na orientacao da sonda, mas deixa a responsabilidade de mover para a propria sonda

2022-09-27 11:24 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
> +    public void desativar(Boolean estaAtivo) {
realmente heeh acho que eu estava muito ligado a logica de setter

2022-09-27 11:24 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
> +    public enum direcao {
alterado

2022-09-27 11:25 UTC, AmaralUSP commented on sonda/src/main/java/com/elo7/testJr/sonda/repository/SondaRepository.java
> +
mudei a responsabilidade para dentro das entdades

2022-09-27 12:59 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/SondaExceptions/SondaExceptions.java
> +public class SondaExceptions extends RuntimeException{
Uma classe final é uma classe que não pode ser herdada, já que o sealed força somente os arquivos internos a implementarem a classe, nada mais justo que quem for filho desta, também não poder ser herdada.

2022-09-27 14:01 UTC, danielqejo commented on sonda/src/main/java/com/elo7/testJr/sonda/entity/Sonda.java
>      private Campo campo;
Não é estritamente necessário, mas se o campo não será utilizado pela Sonda podemos só manter a referência.

2022-09-27 14:08 UTC, danielqejo commented on src/main/java/com/elo7/testjr/campo/repository/CampoRepository.java
>  import org.springframework.data.repository.query.Param;
O metodo estaDentroDoCampo não é mais utilizado.

2022-09-27 14:08 UTC, danielqejo commented on src/main/java/com/elo7/testjr/sonda/repository/SondaRepository.java
>      @Query("SELECT id from Sonda where posAtualX = :x AND posAtualY = :y AND campo_id = :id AND estaAtivo = true")
Métodos não mais utilizados.

2022-09-27 20:03 UTC, AmaralUSP commented on src/main/java/com/elo7/testjr/campo/Model/CampoService.java
> +    }
ok!

2022-09-27 20:04 UTC, AmaralUSP commented on src/main/java/com/elo7/testjr/campo/Model/CampoService.java
> +    }
ok

2022-09-27 20:05 UTC, AmaralUSP commented on src/main/java/com/elo7/testjr/campo/controller/CampoController.java
> +    @ResponseStatus(HttpStatus.CREATED)
realmente, esta redundante e nos casos de erro o handler sobreescreve usando essa anotacao! faz sentido

2022-09-27 20:12 UTC, AmaralUSP commented on src/main/java/com/elo7/testjr/sonda/Model/SondaService.java
> +    }
resolvido

2022-09-27 20:15 UTC, AmaralUSP commented on src/main/java/com/elo7/testjr/campo/controller/CampoController.java
> +        return ResponseEntity.ok(campo.get());
mudei um pouco a forma de tratar, deixei a verificacao do optional no service, caso esteja vazio solta uma excessao, caso contrario retorna um campo!

2022-09-27 20:33 UTC, AmaralUSP commented on src/main/java/com/elo7/testjr/campo/entity/Campo.java
> +        }
achei essa opcao @Transactional(dontRollbackOn = {SondaExceptions.SondaSaiuDoEspacoObservavelExceptions.class, SondaExceptions.SondaColidiuException.class}) que ele nao faz o rollback, entao da pra soltar a excessao e desativar a sonda!

2022-09-27 20:39 UTC, AmaralUSP commented on src/main/java/com/elo7/testjr/sonda/repository/SondaRepository.java
> +    default void salvaMovimento(@Param("id") Long id, @Param("x") int x, @Param("y") int y) {}
nenhum motivo em especial, era so pq tinha centralizado as operacoes no banco, mas agora estou usando os metodos do jpa

2022-09-29 19:11 UTC, merged